fluent-bit/fluent-bit-4.2.0.tar.gz:
  size: 38635664
  object_id: 69c32c80-19d7-418d-66b2-69eb691f8dc5
  sha: sha256:44fe0f52e89a63b213695748f99691d0a6247a4bd05065f1b517c798d9f89bcc
krb5/krb5-1.22.1.tar.gz:
  size: 44380160
  object_id: 06cc4891-5a9c-4a10-772d-d587e2736923
  sha: sha256:6d163bd93bf4f4ab430339e009d348d7cbd0e87470bdb4ca1b2c63b02d498d4c
telemetry-cli/telemetry-cli-linux-2.3.0:
  size: 17346178
  object_id: f92c11d7-d391-4a2d-4d61-b376f92d2613
  sha: sha256:0ddecc9117be98d08a8060713cca0a4075275766512c22c9173d88f583a4a98a
