fluent-bit/fluent-bit-4.2.0.tar.gz:
  size: 38635664
  object_id: 69c32c80-19d7-418d-66b2-69eb691f8dc5
  sha: sha256:44fe0f52e89a63b213695748f99691d0a6247a4bd05065f1b517c798d9f89bcc
krb5/krb5-1.22.1.tar.gz:
  size: 8801023
  object_id: 8b77d35c-c02b-4c7b-7ccc-997f0277df99
  sha: sha256:49d6203da145df1c02e5c5681b405b1110a8fe1c1f2b8cb1c894acf58ddd7ae6
telemetry-cli/telemetry-cli-linux-2.4.0-dev.build.17:
  size: 17149354
  object_id: 30c84ab5-e93a-4176-602b-a0236d2c6775
  sha: sha256:099a28c6d04f216a03c0a136cc77a88109561ba80f7801af61830e80b9b0308a
