fluent-bit/fluent-bit-4.2.2.tar.gz:
  size: 38790530
  object_id: bf228ad6-1130-4abb-404b-32f6ebc8fb37
  sha: sha256:5d8e642be576985ad8123609c32d5ac44a9d3dad9eafcdc14208622444b5a4f0
krb5/krb5-1.22.2.tar.gz:
  size: 8747729
  object_id: ac56b023-5dce-41cc-4981-a48bfa4e7493
  sha: sha256:3243ffbc8ea4d4ac22ddc7dd2a1dc54c57874c40648b60ff97009763554eaf13
telemetry-cli/telemetry-cli-linux-2.4.1:
  size: 17230821
  object_id: 1708869c-2a75-4512-7ef9-783b2c24bf34
  sha: sha256:a27f6b2c0345d13087066a075da67bc5fbd85ebe3a4e24e6cc66d646ca0c449b
