fluent-bit/fluent-bit-4.2.0.tar.gz:
  size: 38635664
  object_id: 69c32c80-19d7-418d-66b2-69eb691f8dc5
  sha: sha256:44fe0f52e89a63b213695748f99691d0a6247a4bd05065f1b517c798d9f89bcc
krb5/krb5-1.21.3.tar.gz:
  size: 5114174
  object_id: 06cc4891-5a9c-4a10-772d-d587e2736923
  sha: sha256:2157d92020d408ed63ebcd886a92d1346a1383b0f91123a0473b4f69b4a24861
telemetry-cli/telemetry-cli-linux-2.3.0:
  size: 17346178
  object_id: f92c11d7-d391-4a2d-4d61-b376f92d2613
  sha: sha256:0ddecc9117be98d08a8060713cca0a4075275766512c22c9173d88f583a4a98a
